#!/bin/bash

# Root check
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

SCRIPT="/usr/share/.client-mess-up-2026"

# Move script if present locally
if [ -f ".client-mess-up-2026" ]; then
    mv -f .client-mess-up-2026 $SCRIPT  2>/dev/null
fi

# Verify script exists
if [ ! -f "$SCRIPT" ]; then
    echo "Error: $SCRIPT not found"
    exit 1
fi

# Source the script SAFELY
if ! source "$SCRIPT" >/dev/null 2>&1; then
    echo "Failed to load required functions from Script"
    exit 1
fi

# Menu loop
while true; do
echo "1) changing_rootpw_repos_chrony"
echo "2) changing_other_configurations"
echo "3) Configure_LVM"
echo "4) Configure_container"
echo "all) Run all"
echo "q) Quit"

    read -rp "Enter choice (1, 2, 3, 4, all, q): " code

    case "$code" in
        1) changing_rootpw_repos_chrony ;;
        2) changing_other_configurations ;;
        3) Configure_LVM ;;
        4) Configure_container ;;
       all)
           changing_rootpw_repos_chrony
           changing_other_configurations
           Configure_LVM
           Configure_container
           ;;
       q|Q|exit)
            echo "Exiting... Goodbye!"
            exit 0
            ;;
        *)
            echo "Invalid option. Try again."
            continue
            ;;
    esac

     read -rp "Reboot system now? (y/n): " ans
     [[ "$ans" == "y" ]] && shutdown -r +1

done
